import { AGENT_IDENTITY, RESPONSE_RULES } from './Core/BaseRules';
import { SUPPORT_AREAS, IMPORTANT_RULES, PROHIBITED_PHRASES, ADDITIONAL_CONTEXT } from './Core/SupportAreas';
import { SPORTS_BET_FLOW } from './Flows/SportsBetFlow';
import { BETTING_ASSISTANT_FLOW } from './Flows/BettingAssistantFlow';

export const CUSTOMER_SERVICE_AGENT_PROMPT = `${AGENT_IDENTITY}

${RESPONSE_RULES}

${SUPPORT_AREAS}

${SPORTS_BET_FLOW}

${BETTING_ASSISTANT_FLOW}

${IMPORTANT_RULES}

${PROHIBITED_PHRASES}

${ADDITIONAL_CONTEXT}`;

export const getCustomerServicePrompt = (): string => CUSTOMER_SERVICE_AGENT_PROMPT;

// Exportaciones individuales para casos de uso específicos
export {
  AGENT_IDENTITY,
  RESPONSE_RULES,
  SUPPORT_AREAS,
  IMPORTANT_RULES,
  PROHIBITED_PHRASES,
  ADDITIONAL_CONTEXT,
  SPORTS_BET_FLOW,
  BETTING_ASSISTANT_FLOW,
};
