import { SportsbookBanner, SportsbookEvent, SportsbookRecommendation } from '../../interfaces/SportsbookInterfaces';

export const SportsbookLocalization = {
  pageTitle: 'Smart Sportbook',
  pageDescription: 'Mercados en vivo con atención instantanea.',
  openChatLabel: 'Abrir chat',
  closeChatLabel: 'Cerrar chat',
  bottomCounterLabel: 'Apuestas realizadas',
  addBetLabel: 'Agregar apuesta',
  banners: [
    {
      id: 'banner-1',
      title: 'Bono de bienvenida',
      subtitle: 'Recibe hasta 100% en tu primer deposito.',
      ctaLabel: 'Activar bono',
    },
    {
      id: 'banner-2',
      title: 'Super cuota caliente',
      subtitle: 'Seleccion diaria con cuota mejorada.',
      ctaLabel: 'Ver seleccion',
    },
    {
      id: 'banner-3',
      title: 'Cashout rapido',
      subtitle: 'Cierra tu apuesta cuando quieras.',
      ctaLabel: 'Saber mas',
    },
  ] satisfies SportsbookBanner[],
  events: [
    {
      id: 'event-1',
      league: 'Premier League',
      homeTeam: 'Chelsea',
      awayTeam: 'Barcelona',
      minute: "85'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.10' },
        { id: 'x', label: 'X', odds: '4.10' },
        { id: '2', label: '2', odds: '1.30' },
      ],
    },
    {
      id: 'event-2',
      league: 'Premier League',
      homeTeam: 'Arsenal FC',
      awayTeam: 'Morecambe',
      minute: "86'",
      marketOptions: [
        { id: '1', label: '1', odds: '3.20' },
        { id: 'x', label: 'X', odds: '1.45' },
        { id: '2', label: '2', odds: '16.00' },
      ],
    },
    {
      id: 'event-3',
      league: 'National League',
      homeTeam: 'Braintree Town FC',
      awayTeam: 'Southport',
      minute: "87'",
      marketOptions: [
        { id: '1', label: '1', odds: '4.33' },
        { id: 'x', label: 'X', odds: '1.41' },
        { id: '2', label: '2', odds: '7.00' },
      ],
    },
    {
      id: 'event-4',
      league: 'National League',
      homeTeam: 'Altrincham',
      awayTeam: 'Eastleigh FC',
      minute: "89'",
      marketOptions: [
        { id: '1', label: '1', odds: '4.50' },
        { id: 'x', label: 'X', odds: '1.31' },
        { id: '2', label: '2', odds: '10.00' },
      ],
    },
    {
      id: 'event-5',
      league: 'Serie A',
      homeTeam: 'AC Milan',
      awayTeam: 'Inter Milan',
      minute: "67'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.85' },
        { id: 'x', label: 'X', odds: '3.20' },
        { id: '2', label: '2', odds: '2.55' },
      ],
    },
    {
      id: 'event-6',
      league: 'Bundesliga',
      homeTeam: 'Bayern Munich',
      awayTeam: 'Borussia Dortmund',
      minute: "45'",
      marketOptions: [
        { id: '1', label: '1', odds: '1.75' },
        { id: 'x', label: 'X', odds: '3.80' },
        { id: '2', label: '2', odds: '4.20' },
      ],
    },
    {
      id: 'event-7',
      league: 'La Liga',
      homeTeam: 'Real Madrid',
      awayTeam: 'Atletico Madrid',
      minute: "32'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.15' },
        { id: 'x', label: 'X', odds: '3.25' },
        { id: '2', label: '2', odds: '3.40' },
      ],
    },
    {
      id: 'event-8',
      league: 'Ligue 1',
      homeTeam: 'Paris Saint-Germain',
      awayTeam: 'Olympique Lyon',
      minute: "54'",
      marketOptions: [
        { id: '1', label: '1', odds: '1.55' },
        { id: 'x', label: 'X', odds: '4.00' },
        { id: '2', label: '2', odds: '5.50' },
      ],
    },
    {
      id: 'event-9',
      league: 'Premier League',
      homeTeam: 'Liverpool',
      awayTeam: 'Manchester United',
      minute: "72'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.40' },
        { id: 'x', label: 'X', odds: '3.30' },
        { id: '2', label: '2', odds: '2.90' },
      ],
    },
    {
      id: 'event-10',
      league: 'Serie A',
      homeTeam: 'Juventus',
      awayTeam: 'AS Roma',
      minute: "41'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.25' },
        { id: 'x', label: 'X', odds: '3.15' },
        { id: '2', label: '2', odds: '3.25' },
      ],
    },
    {
      id: 'event-11',
      league: 'Bundesliga',
      homeTeam: 'RB Leipzig',
      awayTeam: 'Bayer Leverkusen',
      minute: "58'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.65' },
        { id: 'x', label: 'X', odds: '3.40' },
        { id: '2', label: '2', odds: '2.50' },
      ],
    },
    {
      id: 'event-12',
      league: 'La Liga',
      homeTeam: 'Barcelona',
      awayTeam: 'Sevilla',
      minute: "23'",
      marketOptions: [
        { id: '1', label: '1', odds: '1.45' },
        { id: 'x', label: 'X', odds: '4.50' },
        { id: '2', label: '2', odds: '6.00' },
      ],
    },
    {
      id: 'event-13',
      league: 'Premier League',
      homeTeam: 'Manchester City',
      awayTeam: 'Tottenham',
      minute: "36'",
      marketOptions: [
        { id: '1', label: '1', odds: '1.65' },
        { id: 'x', label: 'X', odds: '3.75' },
        { id: '2', label: '2', odds: '5.00' },
      ],
    },
    {
      id: 'event-14',
      league: 'Ligue 1',
      homeTeam: 'Monaco',
      awayTeam: 'Marseille',
      minute: "61'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.20' },
        { id: 'x', label: 'X', odds: '3.25' },
        { id: '2', label: '2', odds: '3.30' },
      ],
    },
    {
      id: 'event-15',
      league: 'Serie A',
      homeTeam: 'Napoli',
      awayTeam: 'Lazio',
      minute: "48'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.00' },
        { id: 'x', label: 'X', odds: '3.50' },
        { id: '2', label: '2', odds: '3.60' },
      ],
    },
    {
      id: 'event-16',
      league: 'Eredivisie',
      homeTeam: 'Ajax',
      awayTeam: 'PSV Eindhoven',
      minute: "29'",
      marketOptions: [
        { id: '1', label: '1', odds: '2.35' },
        { id: 'x', label: 'X', odds: '3.45' },
        { id: '2', label: '2', odds: '2.75' },
      ],
    },
  ] satisfies SportsbookEvent[],
  recommendations: [
    {
      id: 'rec-1',
      eventId: 'event-6',
      homeTeam: 'Bayern Munich',
      awayTeam: 'Borussia Dortmund',
      league: 'Bundesliga',
      selection: '1',
      odds: '1.75',
      riskLevel: 'conservative',
      reasoning: 'Bayern tiene ventaja en el partido y jugara en casa. Historial favorable contra Dortmund.',
    },
    {
      id: 'rec-2',
      eventId: 'event-1',
      homeTeam: 'Chelsea',
      awayTeam: 'Barcelona',
      league: 'Premier League',
      selection: 'X',
      odds: '4.10',
      riskLevel: 'moderate',
      reasoning: 'Partido equilibrado entre dos gigantes europeos. La cuota por empate es atractiva.',
    },
    {
      id: 'rec-3',
      eventId: 'event-2',
      homeTeam: 'Arsenal FC',
      awayTeam: 'Morecambe',
      league: 'Premier League',
      selection: '1',
      odds: '3.20',
      riskLevel: 'risky',
      reasoning: 'Arsenal devrait gagner facilement, mais la difference de niveau pourrait creer des surprises. Cuota alta para el favorito.',
    },
    {
      id: 'rec-4',
      eventId: 'event-5',
      homeTeam: 'AC Milan',
      awayTeam: 'Inter Milan',
      league: 'Serie A',
      selection: 'X',
      odds: '3.20',
      riskLevel: 'moderate',
      reasoning: 'Derby de Milan muy parejas. Ambos equipos en buena forma, el empate tiene buena cuota.',
    },
  ] satisfies SportsbookRecommendation[],
  weeklyRecommendations: [
    {
      id: 'weekly-1',
      eventId: 'event-7',
      homeTeam: 'Real Madrid',
      awayTeam: 'Atletico Madrid',
      league: 'La Liga',
      selection: '1',
      odds: '2.15',
      riskLevel: 'moderate',
      reasoning: 'El derbi madrileno favorece al Real Madrid en su estadio. Apuesta solida para la semana.',
    },
    {
      id: 'weekly-2',
      eventId: 'event-8',
      homeTeam: 'Paris Saint-Germain',
      awayTeam: 'Olympique Lyon',
      league: 'Ligue 1',
      selection: '1',
      odds: '1.55',
      riskLevel: 'conservative',
      reasoning: 'PSG es favorito claro en casa. Baja riesgo con cuota solida.',
    },
    {
      id: 'weekly-3',
      eventId: 'event-9',
      homeTeam: 'Liverpool',
      awayTeam: 'Manchester United',
      league: 'Premier League',
      selection: '2',
      odds: '2.90',
      riskLevel: 'risky',
      reasoning: 'United puede surpreder en Anfield. Cuota interesante para apostantes arriesgados.',
    },
  ] satisfies SportsbookRecommendation[],
};
