export const ChatbotLocalization = {
  title: 'Asistente de Apuestas Deportivas',
  subtitle: '¿En qué evento deportivo te ayudo hoy?',
  inputPlaceholder: 'Escribe tu mensaje...',
  sendButtonAriaLabel: 'Enviar mensaje',
  emptyStateMessage: 'Inicia una conversación escribiendo un mensaje abajo.',
  loadingMessage: 'Pensando...',
  errorMessage: 'Algo salió mal. Por favor intenta nuevamente.',
  retryButton: 'Reintentar',
  newChatButton: 'Nueva conversación',
  helperText: 'Presiona Enter para enviar, Shift + Enter para nueva línea',
  helpTitle: 'Cómo usar el chat',
  helpContent: [
    '💬 Escribe tu pregunta y presiona Enter para enviar',
    '🔄 Usa "Nueva conversación" para empezar un nuevo chat',
    '🌙 Haz clic en el botón de la luna para modo oscuro',
    '💾 Tu conversación se guarda automáticamente',
    '❓ Usa las sugerencias rápidas para preguntas comunes',
  ],
  suggestions: [
    '¿Qué partidos me recomiendas para hoy?',
    '¿Cómo hago una apuesta combinada?',
    'Explícame los tipos de apuestas deportivas',
    '¿Cómo funciona el handicap en fútbol?',
    'Quiero hacer mi primera apuesta deportiva',
    '¿Qué es el over/under en apuestas?',
    'Mi apuesta aparece suspendida',
    '¿Cómo calculo las ganancias de una combinada?',
  ],
} as const;
