export const ChatbotLocalization = {
  title: 'Soporte Lucky Casino',
  subtitle: '¿En qué puedo ayudarte hoy?',
  inputPlaceholder: 'Escribe tu mensaje...',
  sendButtonAriaLabel: 'Enviar mensaje',
  emptyStateMessage: 'Inicia una conversación escribiendo un mensaje abajo.',
  loadingMessage: 'Pensando...',
  errorMessage: 'Algo salió mal. Por favor intenta nuevamente.',
  retryButton: 'Reintentar',
  newChatButton: 'Nueva conversación',
  helperText: 'Presiona Enter para enviar, Shift + Enter para nueva línea',
  helpTitle: 'Cómo usar el chat',
  helpContent: [
    '💬 Escribe tu pregunta y presiona Enter para enviar',
    '🔄 Usa "Nueva conversación" para empezar un nuevo chat',
    '🌙 Haz clic en el botón de la luna para modo oscuro',
    '💾 Tu conversación se guarda automáticamente',
    '❓ Usa las sugerencias rápidas para preguntas comunes',
  ],
  suggestions: [
    '¿Cómo hago un depósito con mi tarjeta de crédito?',
    'Mi retiro está tardando más de lo esperado',
    '¿Cómo reclamo el bono de bienvenida?',
    'El juego se congeló durante una partida',
  ],
} as const;
